--------------------------------------------------------
--  Fichier créé - mardi-février-13-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ABONNEMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ABONNEMENT" 
   (	"ID_UTILISATEUR" NUMBER(*,0), 
	"ID_TOURNOI" NUMBER(*,0), 
	"ID_RENCONTRE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADRESSE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ADRESSE" 
   (	"ID_ADRESSE" NUMBER(*,0), 
	"NOM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPLEXE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."COMPLEXE" 
   (	"ID_COMPLEXE" NUMBER(*,0), 
	"NOM" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."COURT" 
   (	"ID_COURT" NUMBER(*,0), 
	"NOM" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"ID_COMPLEXE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DROIT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."DROIT" 
   (	"ID_DROIT" NUMBER(*,0), 
	"ROLE" VARCHAR2(50 BYTE), 
	"TABLE_DROIT" VARCHAR2(50 BYTE), 
	"GENERAL_DROIT" VARCHAR2(50 BYTE), 
	"COMPLEMENTAIRE_DROIT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EQUIJOU
--------------------------------------------------------

  CREATE TABLE "ADMIN"."EQUIJOU" 
   (	"ID_JOUEUR" NUMBER(*,0), 
	"ID_EQUIPE" NUMBER(*,0), 
	"SCORE_ACTUEL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EQUIPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."EQUIPE" 
   (	"ID_EQUIPE" NUMBER(*,0), 
	"ID_JOUEUR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENEMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."EVENEMENT" 
   (	"ID_EVENEMENT" NUMBER(*,0), 
	"ID_JOUEUR" NUMBER(*,0), 
	"TYPE" VARCHAR2(50 BYTE), 
	"SCORE" VARCHAR2(50 BYTE), 
	"REUSSIS" VARCHAR2(50 BYTE), 
	"DATE_EVENEMENT" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JEU_MATCH
--------------------------------------------------------

  CREATE TABLE "ADMIN"."JEU_MATCH" 
   (	"ID_JEU" NUMBER(*,0), 
	"ID_SET" NUMBER(*,0), 
	"DATE_JEU" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JOUEUR
--------------------------------------------------------

  CREATE TABLE "ADMIN"."JOUEUR" 
   (	"ID_JOUEUR" NUMBER(*,0), 
	"CLASSEMENT" VARCHAR2(50 BYTE), 
	"NATIONALITE" VARCHAR2(50 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NIVEAU
--------------------------------------------------------

  CREATE TABLE "ADMIN"."NIVEAU" 
   (	"VALEUR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORGANISATION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ORGANISATION" 
   (	"ID_USER" NUMBER(*,0), 
	"ID_RENCONTRE" NUMBER(*,0), 
	"ID_TOURNOI" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHASE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PHASE" 
   (	"ID_PHASE" NUMBER(*,0), 
	"NOM" VARCHAR2(50 BYTE), 
	"NOMBRE_MAX_RENCONTRE" NUMBER(*,0), 
	"ID_RENCONTRE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POINT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."POINT" 
   (	"VALEUR" VARCHAR2(20 BYTE), 
	"ID_POINT_ENUM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POINT_MATCH
--------------------------------------------------------

  CREATE TABLE "ADMIN"."POINT_MATCH" 
   (	"ID_POINT" NUMBER(*,0), 
	"ID_JEU" NUMBER(*,0), 
	"ID_EQUIPE" NUMBER(*,0), 
	"DATE_POINT" DATE DEFAULT sysdate, 
	"ID_POINT_ENUMERATION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RENCONTRE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RENCONTRE" 
   (	"ID_RENCONTRE" NUMBER(*,0), 
	"DATE_DEBUT" DATE DEFAULT sysdate, 
	"ID_EQUIPE_UNE" NUMBER(*,0), 
	"ID_EQUIPE_DEUX" NUMBER(*,0), 
	"ID_ARBITRE" NUMBER(*,0), 
	"ID_COURT" NUMBER(*,0), 
	"ID_PHASE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ROLE" 
   (	"NOM" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SET_MATCH
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SET_MATCH" 
   (	"ID_SET" NUMBER(*,0), 
	"ID_RENCONTRE" NUMBER(*,0), 
	"DATE_SET" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TOURNOI
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TOURNOI" 
   (	"ID_TOURNOI" NUMBER(*,0), 
	"NOM" VARCHAR2(50 BYTE), 
	"DATE_TOURNOI" DATE, 
	"NIVEAU" VARCHAR2(50 BYTE), 
	"ID_COMPLEXE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYPE_COURT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TYPE_COURT" 
   (	"VALEUR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYPE_EVENEMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TYPE_EVENEMENT" 
   (	"VALEUR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UTILISATEUR
--------------------------------------------------------

  CREATE TABLE "ADMIN"."UTILISATEUR" 
   (	"ID_UTILISATEUR" NUMBER(*,0), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"ROLE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VILLE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."VILLE" 
   (	"NOM" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence ADRESSE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."ADRESSE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMPLEXE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."COMPLEXE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COURT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."COURT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DROIT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."DROIT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EQUIPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."EQUIPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EVENEMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."EVENEMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence JEU_MATCH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."JEU_MATCH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence JOUEUR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."JOUEUR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PHASE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."PHASE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence POINT_MATCH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."POINT_MATCH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence POINT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."POINT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RENCONTRE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."RENCONTRE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SET_MATCH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."SET_MATCH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TOURNOI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."TOURNOI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence UTILISATEUR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."UTILISATEUR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into ADMIN.ABONNEMENT
SET DEFINE OFF;
REM INSERTING into ADMIN.ADRESSE
SET DEFINE OFF;
REM INSERTING into ADMIN.COMPLEXE
SET DEFINE OFF;
REM INSERTING into ADMIN.COURT
SET DEFINE OFF;
REM INSERTING into ADMIN.DROIT
SET DEFINE OFF;
REM INSERTING into ADMIN.EQUIJOU
SET DEFINE OFF;
REM INSERTING into ADMIN.EQUIPE
SET DEFINE OFF;
REM INSERTING into ADMIN.EVENEMENT
SET DEFINE OFF;
REM INSERTING into ADMIN.JEU_MATCH
SET DEFINE OFF;
REM INSERTING into ADMIN.JOUEUR
SET DEFINE OFF;
REM INSERTING into ADMIN.NIVEAU
SET DEFINE OFF;
REM INSERTING into ADMIN.ORGANISATION
SET DEFINE OFF;
REM INSERTING into ADMIN.PHASE
SET DEFINE OFF;
REM INSERTING into ADMIN.POINT
SET DEFINE OFF;
REM INSERTING into ADMIN.POINT_MATCH
SET DEFINE OFF;
REM INSERTING into ADMIN.RENCONTRE
SET DEFINE OFF;
REM INSERTING into ADMIN.ROLE
SET DEFINE OFF;
REM INSERTING into ADMIN.SET_MATCH
SET DEFINE OFF;
REM INSERTING into ADMIN.TOURNOI
SET DEFINE OFF;
REM INSERTING into ADMIN.TYPE_COURT
SET DEFINE OFF;
REM INSERTING into ADMIN.TYPE_EVENEMENT
SET DEFINE OFF;
REM INSERTING into ADMIN.UTILISATEUR
SET DEFINE OFF;
REM INSERTING into ADMIN.VILLE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index JEU_MATCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."JEU_MATCH_PK" ON "ADMIN"."JEU_MATCH" ("ID_JEU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TOURNOI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."TOURNOI_PK" ON "ADMIN"."TOURNOI" ("ID_TOURNOI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPE_EVENEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."TYPE_EVENEMENT_PK" ON "ADMIN"."TYPE_EVENEMENT" ("VALEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DROIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."DROIT_PK" ON "ADMIN"."DROIT" ("ID_DROIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."EVENEMENT_PK" ON "ADMIN"."EVENEMENT" ("ID_EVENEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RENCONTRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."RENCONTRE_PK" ON "ADMIN"."RENCONTRE" ("ID_RENCONTRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EQUIPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."EQUIPE_PK" ON "ADMIN"."EQUIPE" ("ID_EQUIPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMPLEXE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."COMPLEXE_PK" ON "ADMIN"."COMPLEXE" ("ID_COMPLEXE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SET_MATCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SET_MATCH_PK" ON "ADMIN"."SET_MATCH" ("ID_SET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POINT_MATCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."POINT_MATCH_PK" ON "ADMIN"."POINT_MATCH" ("ID_POINT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VILLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."VILLE_PK" ON "ADMIN"."VILLE" ("NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADRESSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."ADRESSE_PK" ON "ADMIN"."ADRESSE" ("ID_ADRESSE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JOUEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."JOUEUR_PK" ON "ADMIN"."JOUEUR" ("ID_JOUEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NIVEAU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."NIVEAU_PK" ON "ADMIN"."NIVEAU" ("VALEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_UTILISATEUR
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PK_ID_UTILISATEUR" ON "ADMIN"."UTILISATEUR" ("ID_UTILISATEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."ROLE_PK1" ON "ADMIN"."ROLE" ("NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COURT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."COURT_PK" ON "ADMIN"."COURT" ("ID_COURT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PHASE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PHASE_PK" ON "ADMIN"."PHASE" ("ID_PHASE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPE_COURT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."TYPE_COURT_PK" ON "ADMIN"."TYPE_COURT" ("VALEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POINT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."POINT_PK" ON "ADMIN"."POINT" ("ID_POINT_ENUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ADRESSE_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."ADRESSE_INCREMENT" 
    BEFORE INSERT ON ADRESSE
    FOR EACH ROW
    
    BEGIN
      SELECT ADRESSE_SEQ.NEXTVAL
      INTO   :new.ID_ADRESSE
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."ADRESSE_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMPLEXE_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."COMPLEXE_INCREMENT" 
    BEFORE INSERT ON COMPLEXE
    FOR EACH ROW
    
    BEGIN
      SELECT COMPLEXE_SEQ.NEXTVAL
      INTO   :new.ID_COMPLEXE
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."COMPLEXE_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COURT_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."COURT_INCREMENT" 
    BEFORE INSERT ON COURT
    FOR EACH ROW
    
    BEGIN
      SELECT COURT_SEQ.NEXTVAL
      INTO   :new.ID_COURT
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."COURT_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DROIT_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."DROIT_INCREMENT" 
    BEFORE INSERT ON DROIT
    FOR EACH ROW
    
    BEGIN
      SELECT DROIT_SEQ.NEXTVAL
      INTO   :new.ID_DROIT
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."DROIT_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EQUIPE_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."EQUIPE_INCREMENT" 
    BEFORE INSERT ON EQUIPE
    FOR EACH ROW
    
    BEGIN
      SELECT EQUIPE_SEQ.NEXTVAL
      INTO   :new.ID_EQUIPE
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."EQUIPE_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EVENEMENT_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."EVENEMENT_INCREMENT" 
    BEFORE INSERT ON EVENEMENT
    FOR EACH ROW
    
    BEGIN
      SELECT EVENEMENT_SEQ.NEXTVAL
      INTO   :new.ID_EVENEMENT
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."EVENEMENT_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JEU_MATCH_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."JEU_MATCH_INCREMENT" 
    BEFORE INSERT ON JEU_MATCH
    FOR EACH ROW
    
    BEGIN
      SELECT JEU_MATCH_SEQ.NEXTVAL
      INTO   :new.ID_JEU
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."JEU_MATCH_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JOUEUR_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."JOUEUR_INCREMENT" 
    BEFORE INSERT ON JOUEUR
    FOR EACH ROW
    
    BEGIN
      SELECT JOUEUR_SEQ.NEXTVAL
      INTO   :new.ID_JOUEUR
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."JOUEUR_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PHASE_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."PHASE_INCREMENT" 
    BEFORE INSERT ON PHASE
    FOR EACH ROW
    
    BEGIN
      SELECT PHASE_SEQ.NEXTVAL
      INTO   :new.ID_PHASE
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."PHASE_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POINT_MATCH_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."POINT_MATCH_INCREMENT" 
    BEFORE INSERT ON POINT_MATCH
    FOR EACH ROW
    
    BEGIN
      SELECT POINT_MATCH_SEQ.NEXTVAL
      INTO   :new.ID_POINT
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."POINT_MATCH_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POINT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."POINT_TRG" 
BEFORE INSERT ON POINT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_POINT_ENUM IS NULL THEN
      SELECT POINT_SEQ.NEXTVAL INTO :NEW.ID_POINT_ENUM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ADMIN"."POINT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RENCONTRE_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."RENCONTRE_INCREMENT" 
    BEFORE INSERT ON RENCONTRE
    FOR EACH ROW
    
    BEGIN
      SELECT RENCONTRE_SEQ.NEXTVAL
      INTO   :new.ID_RENCONTRE
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."RENCONTRE_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_MATCH_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."SET_MATCH_INCREMENT" 
    BEFORE INSERT ON SET_MATCH
    FOR EACH ROW
    
    BEGIN
      SELECT SET_MATCH_SEQ.NEXTVAL
      INTO   :new.ID_SET
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."SET_MATCH_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TOURNOI_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."TOURNOI_INCREMENT" 
    BEFORE INSERT ON TOURNOI
    FOR EACH ROW
    
    BEGIN
      SELECT TOURNOI_SEQ.NEXTVAL
      INTO   :new.ID_TOURNOI
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."TOURNOI_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UTILISATEUR_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN"."UTILISATEUR_INCREMENT" 
    BEFORE INSERT ON UTILISATEUR
    FOR EACH ROW
    
    BEGIN
      SELECT UTILISATEUR_SEQ.NEXTVAL
      INTO   :new.ID_UTILISATEUR
      FROM   dual;
    END;

/
ALTER TRIGGER "ADMIN"."UTILISATEUR_INCREMENT" ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ROLE" ADD CONSTRAINT "ROLE_PK" PRIMARY KEY ("NOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."ROLE" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EQUIPE" ADD CONSTRAINT "EQUIPE_PK" PRIMARY KEY ("ID_EQUIPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."EQUIPE" MODIFY ("ID_EQUIPE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."EQUIPE" MODIFY ("ID_JOUEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPLEXE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COMPLEXE" ADD CONSTRAINT "COMPLEXE_PK" PRIMARY KEY ("ID_COMPLEXE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."COMPLEXE" MODIFY ("ID_COMPLEXE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NIVEAU
--------------------------------------------------------

  ALTER TABLE "ADMIN"."NIVEAU" ADD CONSTRAINT "NIVEAU_PK" PRIMARY KEY ("VALEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."NIVEAU" MODIFY ("VALEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PHASE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PHASE" ADD CONSTRAINT "PHASE_PK" PRIMARY KEY ("ID_PHASE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."PHASE" MODIFY ("ID_RENCONTRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "ADMIN"."UTILISATEUR" ADD CONSTRAINT "PK_ID_UTILISATEUR" PRIMARY KEY ("ID_UTILISATEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."UTILISATEUR" MODIFY ("ID_UTILISATEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIJOU
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EQUIJOU" MODIFY ("ID_JOUEUR" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."EQUIJOU" MODIFY ("ID_EQUIPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COURT" ADD CONSTRAINT "COURT_PK" PRIMARY KEY ("ID_COURT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."COURT" MODIFY ("ID_COURT" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."COURT" MODIFY ("ID_COMPLEXE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POINT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."POINT" ADD CONSTRAINT "POINT_PK" PRIMARY KEY ("ID_POINT_ENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."POINT" MODIFY ("VALEUR" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."POINT" MODIFY ("ID_POINT_ENUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RENCONTRE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RENCONTRE" ADD CONSTRAINT "RENCONTRE_PK" PRIMARY KEY ("ID_RENCONTRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."RENCONTRE" MODIFY ("ID_RENCONTRE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."RENCONTRE" MODIFY ("ID_EQUIPE_UNE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."RENCONTRE" MODIFY ("ID_EQUIPE_DEUX" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."RENCONTRE" MODIFY ("ID_ARBITRE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."RENCONTRE" MODIFY ("ID_COURT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORGANISATION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ORGANISATION" MODIFY ("ID_USER" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."ORGANISATION" MODIFY ("ID_RENCONTRE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."ORGANISATION" MODIFY ("ID_TOURNOI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOUEUR
--------------------------------------------------------

  ALTER TABLE "ADMIN"."JOUEUR" ADD CONSTRAINT "JOUEUR_PK" PRIMARY KEY ("ID_JOUEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."JOUEUR" MODIFY ("ID_JOUEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENEMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EVENEMENT" ADD CONSTRAINT "EVENEMENT_PK" PRIMARY KEY ("ID_EVENEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."EVENEMENT" MODIFY ("ID_EVENEMENT" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."EVENEMENT" MODIFY ("ID_JOUEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POINT_MATCH
--------------------------------------------------------

  ALTER TABLE "ADMIN"."POINT_MATCH" ADD CONSTRAINT "POINT_MATCH_PK" PRIMARY KEY ("ID_POINT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."POINT_MATCH" MODIFY ("ID_POINT" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."POINT_MATCH" MODIFY ("ID_JEU" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."POINT_MATCH" MODIFY ("ID_EQUIPE" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."POINT_MATCH" MODIFY ("ID_POINT_ENUMERATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VILLE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."VILLE" MODIFY ("NOM" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."VILLE" ADD CONSTRAINT "VILLE_PK" PRIMARY KEY ("NOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JEU_MATCH
--------------------------------------------------------

  ALTER TABLE "ADMIN"."JEU_MATCH" ADD CONSTRAINT "JEU_MATCH_PK" PRIMARY KEY ("ID_JEU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."JEU_MATCH" MODIFY ("ID_JEU" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."JEU_MATCH" MODIFY ("ID_SET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOURNOI
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TOURNOI" MODIFY ("ID_TOURNOI" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."TOURNOI" ADD CONSTRAINT "TOURNOI_PK" PRIMARY KEY ("ID_TOURNOI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TYPE_EVENEMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TYPE_EVENEMENT" MODIFY ("VALEUR" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."TYPE_EVENEMENT" ADD CONSTRAINT "TYPE_EVENEMENT_PK" PRIMARY KEY ("VALEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TYPE_COURT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TYPE_COURT" MODIFY ("VALEUR" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."TYPE_COURT" ADD CONSTRAINT "TYPE_COURT_PK" PRIMARY KEY ("VALEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SET_MATCH
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SET_MATCH" ADD CONSTRAINT "SET_MATCH_PK" PRIMARY KEY ("ID_SET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."SET_MATCH" MODIFY ("ID_SET" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."SET_MATCH" MODIFY ("ID_RENCONTRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADRESSE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ADRESSE" ADD CONSTRAINT "ADRESSE_PK" PRIMARY KEY ("ID_ADRESSE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."ADRESSE" MODIFY ("ID_ADRESSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DROIT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."DROIT" ADD CONSTRAINT "DROIT_PK" PRIMARY KEY ("ID_DROIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN"."DROIT" MODIFY ("ID_DROIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ABONNEMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ABONNEMENT" MODIFY ("ID_UTILISATEUR" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."ABONNEMENT" MODIFY ("ID_TOURNOI" NOT NULL ENABLE);
 
  ALTER TABLE "ADMIN"."ABONNEMENT" MODIFY ("ID_RENCONTRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ABONNEMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ABONNEMENT" ADD CONSTRAINT "FK_ABONNEMENT_ID_RENCONTRE" FOREIGN KEY ("ID_RENCONTRE")
	  REFERENCES "ADMIN"."RENCONTRE" ("ID_RENCONTRE") ENABLE;
 
  ALTER TABLE "ADMIN"."ABONNEMENT" ADD CONSTRAINT "FK_ABONNEMENT_ID_TOURNOI" FOREIGN KEY ("ID_TOURNOI")
	  REFERENCES "ADMIN"."TOURNOI" ("ID_TOURNOI") ENABLE;
 
  ALTER TABLE "ADMIN"."ABONNEMENT" ADD CONSTRAINT "FK_ABONNEMENT_ID_UTILISATEUR" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES "ADMIN"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COURT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COURT" ADD CONSTRAINT "FK_COURT_ID_COMPLEXE" FOREIGN KEY ("ID_COMPLEXE")
	  REFERENCES "ADMIN"."COMPLEXE" ("ID_COMPLEXE") ENABLE;
 
  ALTER TABLE "ADMIN"."COURT" ADD CONSTRAINT "FK_COURT_TYPE" FOREIGN KEY ("TYPE")
	  REFERENCES "ADMIN"."TYPE_COURT" ("VALEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DROIT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."DROIT" ADD CONSTRAINT "FK_DROIT_ROLE" FOREIGN KEY ("ROLE")
	  REFERENCES "ADMIN"."ROLE" ("NOM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIJOU
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EQUIJOU" ADD CONSTRAINT "FK_EQUIJOU_ID_EQUIPE" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "ADMIN"."EQUIPE" ("ID_EQUIPE") ENABLE;
 
  ALTER TABLE "ADMIN"."EQUIJOU" ADD CONSTRAINT "FK_EQUIJOU_ID_JOUEUR" FOREIGN KEY ("ID_JOUEUR")
	  REFERENCES "ADMIN"."JOUEUR" ("ID_JOUEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EQUIPE" ADD CONSTRAINT "FK_EQUIPE_ID_JOUEUR" FOREIGN KEY ("ID_JOUEUR")
	  REFERENCES "ADMIN"."JOUEUR" ("ID_JOUEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENEMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EVENEMENT" ADD CONSTRAINT "FK_EVENEMENT_TYPE" FOREIGN KEY ("TYPE")
	  REFERENCES "ADMIN"."TYPE_EVENEMENT" ("VALEUR") ENABLE;
 
  ALTER TABLE "ADMIN"."EVENEMENT" ADD CONSTRAINT "FK_ID_JOUEUR" FOREIGN KEY ("ID_JOUEUR")
	  REFERENCES "ADMIN"."JOUEUR" ("ID_JOUEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JEU_MATCH
--------------------------------------------------------

  ALTER TABLE "ADMIN"."JEU_MATCH" ADD CONSTRAINT "FK_JEU_MATCH_ID_SET" FOREIGN KEY ("ID_SET")
	  REFERENCES "ADMIN"."SET_MATCH" ("ID_SET") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORGANISATION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_ID_RENCONTRE" FOREIGN KEY ("ID_RENCONTRE")
	  REFERENCES "ADMIN"."RENCONTRE" ("ID_RENCONTRE") ENABLE;
 
  ALTER TABLE "ADMIN"."ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_ID_TOURNOI" FOREIGN KEY ("ID_TOURNOI")
	  REFERENCES "ADMIN"."TOURNOI" ("ID_TOURNOI") ENABLE;
 
  ALTER TABLE "ADMIN"."ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_ID_USER" FOREIGN KEY ("ID_USER")
	  REFERENCES "ADMIN"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHASE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PHASE" ADD CONSTRAINT "FK_PHASE_ID_RENCONTRE" FOREIGN KEY ("ID_RENCONTRE")
	  REFERENCES "ADMIN"."RENCONTRE" ("ID_RENCONTRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POINT_MATCH
--------------------------------------------------------

  ALTER TABLE "ADMIN"."POINT_MATCH" ADD CONSTRAINT "FK_POINT_ID_POINT_ENUM" FOREIGN KEY ("ID_POINT_ENUMERATION")
	  REFERENCES "ADMIN"."POINT" ("ID_POINT_ENUM") ENABLE;
 
  ALTER TABLE "ADMIN"."POINT_MATCH" ADD CONSTRAINT "FK_POINT_MATCH_ID_EQUIPE" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "ADMIN"."EQUIPE" ("ID_EQUIPE") ENABLE;
 
  ALTER TABLE "ADMIN"."POINT_MATCH" ADD CONSTRAINT "FK_POINT_MATCH_ID_JEU" FOREIGN KEY ("ID_JEU")
	  REFERENCES "ADMIN"."JEU_MATCH" ("ID_JEU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RENCONTRE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RENCONTRE" ADD CONSTRAINT "FK_RENCONTRE_ID_ARBITRE" FOREIGN KEY ("ID_ARBITRE")
	  REFERENCES "ADMIN"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE;
 
  ALTER TABLE "ADMIN"."RENCONTRE" ADD CONSTRAINT "FK_RENCONTRE_ID_COURT" FOREIGN KEY ("ID_COURT")
	  REFERENCES "ADMIN"."COURT" ("ID_COURT") ENABLE;
 
  ALTER TABLE "ADMIN"."RENCONTRE" ADD CONSTRAINT "FK_RENCONTRE_ID_EQUIPE_DEUX" FOREIGN KEY ("ID_EQUIPE_DEUX")
	  REFERENCES "ADMIN"."EQUIPE" ("ID_EQUIPE") ENABLE;
 
  ALTER TABLE "ADMIN"."RENCONTRE" ADD CONSTRAINT "FK_RENCONTRE_ID_EQUIPE_UNE" FOREIGN KEY ("ID_EQUIPE_UNE")
	  REFERENCES "ADMIN"."EQUIPE" ("ID_EQUIPE") ENABLE;
 
  ALTER TABLE "ADMIN"."RENCONTRE" ADD CONSTRAINT "PK_RENCONTRE_ID_PHASE" FOREIGN KEY ("ID_PHASE")
	  REFERENCES "ADMIN"."PHASE" ("ID_PHASE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SET_MATCH
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SET_MATCH" ADD CONSTRAINT "FK_SET_MATCH_ID_RENCONTRE" FOREIGN KEY ("ID_RENCONTRE")
	  REFERENCES "ADMIN"."RENCONTRE" ("ID_RENCONTRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TOURNOI
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TOURNOI" ADD CONSTRAINT "FK_TOURNOI_ID_COMPLEXE" FOREIGN KEY ("ID_COMPLEXE")
	  REFERENCES "ADMIN"."COMPLEXE" ("ID_COMPLEXE") ENABLE;
 
  ALTER TABLE "ADMIN"."TOURNOI" ADD CONSTRAINT "FK_TOURNOI_NIVEAU" FOREIGN KEY ("NIVEAU")
	  REFERENCES "ADMIN"."NIVEAU" ("VALEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "ADMIN"."UTILISATEUR" ADD CONSTRAINT "FK_ROLE" FOREIGN KEY ("ROLE")
	  REFERENCES "ADMIN"."ROLE" ("NOM") ENABLE;
