--------------------------------------------------------
--  Fichier cr�� - jeudi-mars-15-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type SCORE_JEU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "PIPELINE"."SCORE_JEU" as object
    (jeu_1 NUMBER,
    jeu_2 NUMBER
    );

/
--------------------------------------------------------
--  DDL for Table ABONNEMENT
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."ABONNEMENT" 
   (	"ID_UTILISATEUR" NUMBER(*,0), 
	"ID_TOURNOI" NUMBER(*,0), 
	"ID_RENCONTRE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADRESSE
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."ADRESSE" 
   (	"ID_ADRESSE" NUMBER(*,0), 
	"NOM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPLEXE
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."COMPLEXE" 
   (	"ID_COMPLEXE" NUMBER(*,0), 
	"NOM" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURT
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."COURT" 
   (	"ID_COURT" NUMBER(*,0), 
	"NOM" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"ID_COMPLEXE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DROIT
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."DROIT" 
   (	"ID_DROIT" NUMBER(38,0), 
	"TABLE_DROIT" VARCHAR2(50 BYTE), 
	"PRIVILEGE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIPELINE" ;
--------------------------------------------------------
--  DDL for Table DROIT_ROLE
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."DROIT_ROLE" 
   (	"ROLE" VARCHAR2(50 BYTE), 
	"ID_DROIT" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIPELINE" ;
--------------------------------------------------------
--  DDL for Table EQUIJOU
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."EQUIJOU" 
   (	"ID_JOUEUR" NUMBER(*,0), 
	"ID_EQUIPE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EQUIPE
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."EQUIPE" 
   (	"ID_EQUIPE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table EVENEMENT
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."EVENEMENT" 
   (	"ID_EVENEMENT" NUMBER(*,0), 
	"ID_JOUEUR" NUMBER(*,0), 
	"TYPE" VARCHAR2(50 BYTE), 
	"SCORE" VARCHAR2(50 BYTE), 
	"REUSSIS" VARCHAR2(50 BYTE), 
	"DATE_EVENEMENT" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JEU_MATCH
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."JEU_MATCH" 
   (	"ID_JEU" NUMBER(*,0), 
	"ID_SET" NUMBER(*,0), 
	"DATE_JEU" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JOUEUR
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."JOUEUR" 
   (	"ID_JOUEUR" NUMBER(*,0), 
	"CLASSEMENT" VARCHAR2(50 BYTE), 
	"NATIONALITE" VARCHAR2(50 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NIVEAU
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."NIVEAU" 
   (	"VALEUR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORGANISATION
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."ORGANISATION" 
   (	"ID_USER" NUMBER(*,0), 
	"ID_RENCONTRE" NUMBER(*,0), 
	"ID_TOURNOI" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHASE
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."PHASE" 
   (	"ID_PHASE" NUMBER(*,0), 
	"NOM" VARCHAR2(50 BYTE), 
	"NOMBRE_MAX_RENCONTRE" NUMBER(*,0), 
	"ID_RENCONTRE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POINT
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."POINT" 
   (	"VALEUR" VARCHAR2(20 BYTE), 
	"ID_POINT_ENUM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POINT_MATCH
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."POINT_MATCH" 
   (	"ID_POINT" NUMBER(*,0), 
	"ID_JEU" NUMBER(*,0), 
	"DATE_POINT" DATE DEFAULT sysdate, 
	"ID_POINT_ENUMERATION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRIVILEGE
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."PRIVILEGE" 
   (	"VALEUR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIPELINE" ;
--------------------------------------------------------
--  DDL for Table RENCONTRE
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."RENCONTRE" 
   (	"ID_RENCONTRE" NUMBER(*,0), 
	"DATE_DEBUT" DATE DEFAULT sysdate, 
	"ID_EQUIPE_UNE" NUMBER(*,0), 
	"ID_EQUIPE_DEUX" NUMBER(*,0), 
	"ID_ARBITRE" NUMBER(*,0), 
	"ID_COURT" NUMBER(*,0), 
	"ID_PHASE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RENCONTRE_EQUIPE
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."RENCONTRE_EQUIPE" 
   (	"ID_RENCONTRE" NUMBER, 
	"ID_EQUIPE" NUMBER, 
	"ID_RENCONTRE_EQUIPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIPELINE" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."ROLE" 
   (	"VALEUR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SET_MATCH
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."SET_MATCH" 
   (	"ID_SET" NUMBER(*,0), 
	"DATE_SET" DATE DEFAULT sysdate, 
	"ID_RENCONTRE_EQUIPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TOURNOI
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."TOURNOI" 
   (	"ID_TOURNOI" NUMBER(*,0), 
	"NOM" VARCHAR2(50 BYTE), 
	"DATE_TOURNOI" DATE, 
	"NIVEAU" VARCHAR2(50 BYTE), 
	"ID_COMPLEXE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYPE_COURT
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."TYPE_COURT" 
   (	"VALEUR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TYPE_EVENEMENT
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."TYPE_EVENEMENT" 
   (	"VALEUR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UTILISATEUR
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."UTILISATEUR" 
   (	"ID_UTILISATEUR" NUMBER(*,0), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"ROLE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VILLE
--------------------------------------------------------

  CREATE TABLE "PIPELINE"."VILLE" 
   (	"VALEUR" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence ADRESSE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."ADRESSE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence COMPLEXE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."COMPLEXE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence COURT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."COURT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence DROIT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."DROIT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence DROIT_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."DROIT_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence EQUIPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."EQUIPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence EVENEMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."EVENEMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence JEU_MATCH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."JEU_MATCH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence JOUEUR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."JOUEUR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence PHASE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."PHASE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence POINT_MATCH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."POINT_MATCH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence POINT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."POINT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence RENCONTRE_EQUIPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."RENCONTRE_EQUIPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence RENCONTRE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."RENCONTRE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SET_MATCH_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."SET_MATCH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence TOURNOI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."TOURNOI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence UTILISATEUR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIPELINE"."UTILISATEUR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE   ;
REM INSERTING into PIPELINE.ABONNEMENT
SET DEFINE OFF;
REM INSERTING into PIPELINE.ADRESSE
SET DEFINE OFF;
REM INSERTING into PIPELINE.COMPLEXE
SET DEFINE OFF;
REM INSERTING into PIPELINE.COURT
SET DEFINE OFF;
REM INSERTING into PIPELINE.DROIT
SET DEFINE OFF;
REM INSERTING into PIPELINE.DROIT_ROLE
SET DEFINE OFF;
REM INSERTING into PIPELINE.EQUIJOU
SET DEFINE OFF;
REM INSERTING into PIPELINE.EQUIPE
SET DEFINE OFF;
REM INSERTING into PIPELINE.EVENEMENT
SET DEFINE OFF;
REM INSERTING into PIPELINE.JEU_MATCH
SET DEFINE OFF;
REM INSERTING into PIPELINE.JOUEUR
SET DEFINE OFF;
REM INSERTING into PIPELINE.NIVEAU
SET DEFINE OFF;
REM INSERTING into PIPELINE.ORGANISATION
SET DEFINE OFF;
REM INSERTING into PIPELINE.PHASE
SET DEFINE OFF;
REM INSERTING into PIPELINE.POINT
SET DEFINE OFF;
REM INSERTING into PIPELINE.POINT_MATCH
SET DEFINE OFF;
REM INSERTING into PIPELINE.PRIVILEGE
SET DEFINE OFF;
REM INSERTING into PIPELINE.RENCONTRE
SET DEFINE OFF;
REM INSERTING into PIPELINE.RENCONTRE_EQUIPE
SET DEFINE OFF;
REM INSERTING into PIPELINE.ROLE
SET DEFINE OFF;
Insert into PIPELINE.ROLE (VALEUR) values ('USERS');
REM INSERTING into PIPELINE.SET_MATCH
SET DEFINE OFF;
REM INSERTING into PIPELINE.TOURNOI
SET DEFINE OFF;
REM INSERTING into PIPELINE.TYPE_COURT
SET DEFINE OFF;
REM INSERTING into PIPELINE.TYPE_EVENEMENT
SET DEFINE OFF;
REM INSERTING into PIPELINE.UTILISATEUR
SET DEFINE OFF;
Insert into PIPELINE.UTILISATEUR (ID_UTILISATEUR,EMAIL,PASSWORD,NOM,PRENOM,ROLE) values ('1','thomas.kint@epsi.fr','password','KINT','THOMAS','USERS');
REM INSERTING into PIPELINE.VILLE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADRESSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."ADRESSE_PK" ON "PIPELINE"."ADRESSE" ("ID_ADRESSE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMPLEXE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."COMPLEXE_PK" ON "PIPELINE"."COMPLEXE" ("ID_COMPLEXE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COURT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."COURT_PK" ON "PIPELINE"."COURT" ("ID_COURT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DROIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."DROIT_PK" ON "PIPELINE"."DROIT" ("ID_DROIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIPELINE" ;
--------------------------------------------------------
--  DDL for Index EQUIPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."EQUIPE_PK" ON "PIPELINE"."EQUIPE" ("ID_EQUIPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."EVENEMENT_PK" ON "PIPELINE"."EVENEMENT" ("ID_EVENEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JEU_MATCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."JEU_MATCH_PK" ON "PIPELINE"."JEU_MATCH" ("ID_JEU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JOUEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."JOUEUR_PK" ON "PIPELINE"."JOUEUR" ("ID_JOUEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NIVEAU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."NIVEAU_PK" ON "PIPELINE"."NIVEAU" ("VALEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PHASE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."PHASE_PK" ON "PIPELINE"."PHASE" ("ID_PHASE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_UTILISATEUR
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."PK_ID_UTILISATEUR" ON "PIPELINE"."UTILISATEUR" ("ID_UTILISATEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POINT_MATCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."POINT_MATCH_PK" ON "PIPELINE"."POINT_MATCH" ("ID_POINT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POINT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."POINT_PK" ON "PIPELINE"."POINT" ("ID_POINT_ENUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRIVILEGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."PRIVILEGE_PK" ON "PIPELINE"."PRIVILEGE" ("VALEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIPELINE" ;
--------------------------------------------------------
--  DDL for Index RENCONTREEQUIPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."RENCONTREEQUIPE_PK" ON "PIPELINE"."RENCONTRE_EQUIPE" ("ID_RENCONTRE_EQUIPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIPELINE" ;
--------------------------------------------------------
--  DDL for Index RENCONTRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."RENCONTRE_PK" ON "PIPELINE"."RENCONTRE" ("ID_RENCONTRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."ROLE_PK1" ON "PIPELINE"."ROLE" ("VALEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SET_MATCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."SET_MATCH_PK" ON "PIPELINE"."SET_MATCH" ("ID_SET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TOURNOI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."TOURNOI_PK" ON "PIPELINE"."TOURNOI" ("ID_TOURNOI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPE_COURT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."TYPE_COURT_PK" ON "PIPELINE"."TYPE_COURT" ("VALEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPE_EVENEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."TYPE_EVENEMENT_PK" ON "PIPELINE"."TYPE_EVENEMENT" ("VALEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VILLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIPELINE"."VILLE_PK" ON "PIPELINE"."VILLE" ("VALEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ADRESSE_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."ADRESSE_INCREMENT" 
    BEFORE INSERT ON ADRESSE
    FOR EACH ROW
    
    BEGIN
      SELECT ADRESSE_SEQ.NEXTVAL
      INTO   :new.ID_ADRESSE
      FROM   dual;
    END;


/
ALTER TRIGGER "PIPELINE"."ADRESSE_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMPLEXE_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."COMPLEXE_INCREMENT" 
    BEFORE INSERT ON COMPLEXE
    FOR EACH ROW
    
    BEGIN
      SELECT COMPLEXE_SEQ.NEXTVAL
      INTO   :new.ID_COMPLEXE
      FROM   dual;
    END;


/
ALTER TRIGGER "PIPELINE"."COMPLEXE_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTROLE_EQUIPE_RENCONTRE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."CONTROLE_EQUIPE_RENCONTRE" 
    BEFORE INSERT
    ON rencontre
    FOR EACH ROW
        
    BEGIN
        IF :new.ID_EQUIPE_UNE = :new.ID_EQUIPE_DEUX THEN
            RAISE_APPLICATION_ERROR( -20003, 'Les deux �quipes sont identiques' );
        END IF;
    END;

/
ALTER TRIGGER "PIPELINE"."CONTROLE_EQUIPE_RENCONTRE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTROLE_EVOLUTION_JEU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."CONTROLE_EVOLUTION_JEU" 
    BEFORE INSERT
    ON jeu_match
    FOR EACH ROW

    DECLARE
        score SCORE_JEU;
        var_id_jeu NUMBER;
    BEGIN
        SELECT ID_JEU INTO var_id_jeu FROM JEU_MATCH WHERE ID_SET = :new.ID_SET AND ROWNUM = 1 ORDER BY ID_JEU DESC;
        score := RECUPERER_SCORE_JEU(var_id_jeu);
        IF (score.jeu_1 - score.jeu_2) > 1 OR (score.jeu_2 - score.jeu_1) > 1 THEN
            IF score.jeu_1 > 5 OR score.jeu_2 > 5 THEN
                INSERT_NOUVEAU_SET(var_id_jeu);
            END IF;
        END IF;
    END;
/
ALTER TRIGGER "PIPELINE"."CONTROLE_EVOLUTION_JEU" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTROLE_EVOLUTION_POINT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."CONTROLE_EVOLUTION_POINT" 
    BEFORE INSERT
    ON point_match
    FOR EACH ROW

    DECLARE
        id_point_equipe_1 number;
        id_point_equipe_2 number;
        nb number;	
        id_equipe_2 number;
        id_set NUMBER;
        cpt_point NUMBER;

    BEGIN
        SELECT id_point_enumeration INTO id_point_equipe_1 FROM point_match WHERE id_equipe = :new.id_equipe AND id_jeu = :new.id_jeu AND ROWNUM = 1 ORDER BY date_point DESC;

        SELECT id_equipe INTO id_equipe_2 FROM point_match WHERE id_jeu = :new.id_jeu and id_equipe <> :new.id_equipe AND ROWNUM = 1;

        SELECT id_point_enumeration INTO id_point_equipe_2 FROM point_match WHERE id_equipe = id_equipe_2 AND id_jeu = :new.id_jeu AND ROWNUM = 1 ORDER BY date_point DESC;

        SELECT COUNT(id_point_enum) INTO nb FROM point;

        SELECT id_set INTO id_set FROM JEU_MATCH WHERE id_jeu = :new.id_jeu;

        SELECT COUNT(ID_POINT) INTO cpt_point FROM POINT_MATCH WHERE ID_JEU = :new.ID_JEU;

        IF cpt_point <> 0 THEN

            IF id_point_equipe_1 = nb - 2 THEN
                insert_nouveau_jeu(:new.id_equipe, id_equipe_2, id_set);
                :new.ID_POINT_ENUMERATION := MOD((id_point_equipe_1 + 1), nb);
            ELSE 
                IF id_point_equipe_1 = nb - 3 AND id_point_equipe_2 = nb - 3 THEN
                    :new.ID_POINT_ENUMERATION := MOD((id_point_equipe_1 + 1), nb);
                ELSE 
                    IF id_point_equipe_1 = nb - 3 AND id_point_equipe_2 = nb - 2 THEN
                        :new.ID_POINT_ENUMERATION := MOD((id_point_equipe_1 - 1), nb);
                        :new.ID_EQUIPE := id_equipe_2;
                    ELSE 
                        IF id_point_equipe_1 = nb - 3 AND id_point_equipe_2 < nb - 3 THEN
                            :new.ID_POINT_ENUMERATION := MOD((id_point_equipe_1 + 2), nb);
                        ELSE
                            :new.ID_POINT_ENUMERATION := MOD((id_point_equipe_1 + 1), nb);
                        END IF;
                    END IF;
                END IF;
            END IF;
        END IF;
    END;
/
ALTER TRIGGER "PIPELINE"."CONTROLE_EVOLUTION_POINT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COURT_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."COURT_INCREMENT" 
    BEFORE INSERT ON COURT
    FOR EACH ROW
    
    BEGIN
      SELECT COURT_SEQ.NEXTVAL
      INTO   :new.ID_COURT
      FROM   dual;
    END;


/
ALTER TRIGGER "PIPELINE"."COURT_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DROIT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."DROIT_TRG" 
BEFORE INSERT ON DROIT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_DROIT IS NULL THEN
      SELECT DROIT_SEQ1.NEXTVAL INTO :NEW.ID_DROIT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PIPELINE"."DROIT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EQUIPE_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."EQUIPE_INCREMENT" 
    BEFORE INSERT ON EQUIPE
    FOR EACH ROW
    
    BEGIN
      SELECT EQUIPE_SEQ.NEXTVAL
      INTO   :new.ID_EQUIPE
      FROM   dual;
    END;


/
ALTER TRIGGER "PIPELINE"."EQUIPE_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EVENEMENT_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."EVENEMENT_INCREMENT" 
    BEFORE INSERT ON EVENEMENT
    FOR EACH ROW
    
    BEGIN
      SELECT EVENEMENT_SEQ.NEXTVAL
      INTO   :new.ID_EVENEMENT
      FROM   dual;
    END;


/
ALTER TRIGGER "PIPELINE"."EVENEMENT_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JEU_MATCH_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."JEU_MATCH_INCREMENT" 
    BEFORE INSERT ON JEU_MATCH
    FOR EACH ROW
    
    BEGIN
      SELECT JEU_MATCH_SEQ.NEXTVAL
      INTO   :new.ID_JEU
      FROM   dual;
    END;


/
ALTER TRIGGER "PIPELINE"."JEU_MATCH_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JOUEUR_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."JOUEUR_INCREMENT" 
    BEFORE INSERT ON JOUEUR
    FOR EACH ROW
    
    BEGIN
      SELECT JOUEUR_SEQ.NEXTVAL
      INTO   :new.ID_JOUEUR
      FROM   dual;
    END;


/
ALTER TRIGGER "PIPELINE"."JOUEUR_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PHASE_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."PHASE_INCREMENT" 
    BEFORE INSERT ON PHASE
    FOR EACH ROW
    
    BEGIN
      SELECT PHASE_SEQ.NEXTVAL
      INTO   :new.ID_PHASE
      FROM   dual;
    END;


/
ALTER TRIGGER "PIPELINE"."PHASE_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POINT_MATCH_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."POINT_MATCH_INCREMENT" 
    BEFORE INSERT ON POINT_MATCH
    FOR EACH ROW
    
    BEGIN
      SELECT POINT_MATCH_SEQ.NEXTVAL
      INTO   :new.ID_POINT
      FROM   dual;
    END;


/
ALTER TRIGGER "PIPELINE"."POINT_MATCH_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POINT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."POINT_TRG" 
BEFORE INSERT ON POINT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_POINT_ENUM IS NULL THEN
      SELECT POINT_SEQ.NEXTVAL INTO :NEW.ID_POINT_ENUM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "PIPELINE"."POINT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RENCONTRE_EQUIPE_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."RENCONTRE_EQUIPE_INCREMENT" 
    BEFORE INSERT ON RENCONTRE_EQUIPE
    FOR EACH ROW
    
    BEGIN
      SELECT RENCONTRE_EQUIPE_SEQ.NEXTVAL
      INTO   :new.ID_RENCONTRE_EQUIPE
      FROM   dual;
    END;

/
ALTER TRIGGER "PIPELINE"."RENCONTRE_EQUIPE_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RENCONTRE_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."RENCONTRE_INCREMENT" 
    BEFORE INSERT ON RENCONTRE
    FOR EACH ROW
    
    BEGIN
      SELECT RENCONTRE_SEQ.NEXTVAL
      INTO   :new.ID_RENCONTRE
      FROM   dual;
    END;



/
ALTER TRIGGER "PIPELINE"."RENCONTRE_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SET_MATCH_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."SET_MATCH_INCREMENT" 
    BEFORE INSERT ON SET_MATCH
    FOR EACH ROW
    
    BEGIN
      SELECT SET_MATCH_SEQ.NEXTVAL
      INTO   :new.ID_SET
      FROM   dual;
    END;


/
ALTER TRIGGER "PIPELINE"."SET_MATCH_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TOURNOI_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."TOURNOI_INCREMENT" 
    BEFORE INSERT ON TOURNOI
    FOR EACH ROW
    
    BEGIN
      SELECT TOURNOI_SEQ.NEXTVAL
      INTO   :new.ID_TOURNOI
      FROM   dual;
    END;


/
ALTER TRIGGER "PIPELINE"."TOURNOI_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UTILISATEUR_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIPELINE"."UTILISATEUR_INCREMENT" 
    BEFORE INSERT ON UTILISATEUR
    FOR EACH ROW
    
    BEGIN
      SELECT UTILISATEUR_SEQ.NEXTVAL
      INTO   :new.ID_UTILISATEUR
      FROM   dual;
    END;


/
ALTER TRIGGER "PIPELINE"."UTILISATEUR_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Procedure INSERT_NOUVEAU_JEU
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PIPELINE"."INSERT_NOUVEAU_JEU" (id_equipe_1 NUMBER, id_equipe_2 NUMBER, id_set NUMBER) IS
    new_id_jeu NUMBER;
   BEGIN
      INSERT INTO jeu_match (id_set) VALUES(id_set);

      SELECT JEU_MATCH_SEQ.CURRVAL INTO new_id_jeu FROM dual;

      INSERT INTO point_match (ID_JEU, ID_EQUIPE, ID_POINT_ENUMERATION) VALUES(new_id_jeu, id_equipe_1, 0);
      INSERT INTO point_match (ID_JEU, ID_EQUIPE, ID_POINT_ENUMERATION) VALUES(new_id_jeu, id_equipe_2, 0);
   END;

/
--------------------------------------------------------
--  DDL for Function RECUPERER_SCORE_JEU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "PIPELINE"."RECUPERER_SCORE_JEU" (param_id_jeu NUMBER) RETURN score_jeu IS
    CURSOR cursor_jeu_set (VAR_ID_SET NUMBER) IS 
        SELECT ID_JEU FROM JEU_MATCH WHERE ID_SET = VAR_ID_SET;
    CURSOR cursor_jeu (VAR_ID_JEU NUMBER) IS 
        SELECT ID_POINT_ENUMERATION, ID_EQUIPE FROM POINT_MATCH WHERE ID_JEU = VAR_ID_JEU;
    ligne_cursor NUMBER;
    ligne_point cursor_jeu%rowtype;
    var_id_set NUMBER;
    var_id_equipe_1 NUMBER;
    var_id_equipe_2 NUMBER;
    cpt_equipe_1 NUMBER := 0;
    cpt_equipe_2 NUMBER := 0;
    BEGIN  
        SELECT ID_SET INTO var_id_set FROM JEU_MATCH WHERE ID_JEU = param_id_jeu;

        SELECT ID_EQUIPE INTO var_id_equipe_1 FROM POINT_MATCH WHERE ID_JEU = param_id_jeu AND ROWNUM = 1 GROUP BY ID_EQUIPE ORDER BY ID_EQUIPE;
        SELECT ID_EQUIPE INTO var_id_equipe_2 FROM POINT_MATCH WHERE ID_JEU = param_id_jeu AND ROWNUM = 1 GROUP BY ID_EQUIPE ORDER BY ID_EQUIPE DESC;

        OPEN cursor_jeu_set(var_id_set);
        LOOP
            FETCH cursor_jeu_set INTO ligne_cursor;

            OPEN cursor_jeu(ligne_cursor);
            LOOP
                FETCH cursor_jeu INTO ligne_point;
                IF ligne_point.ID_POINT_ENUMERATION = 6 THEN
                    IF ligne_point.ID_EQUIPE = var_id_equipe_1 THEN
                        cpt_equipe_1 := cpt_equipe_1 + 1;
                    ELSE
                        cpt_equipe_2 := cpt_equipe_2 + 1;
                    END IF;
                END IF;
            END LOOP;
            CLOSE cursor_jeu;
        END LOOP;
        CLOSE cursor_jeu_set;
    RETURN score_jeu(cpt_equipe_1, cpt_equipe_2);
    END;

/
--------------------------------------------------------
--  Constraints for Table DROIT_ROLE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."DROIT_ROLE" MODIFY ("ID_DROIT" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."DROIT_ROLE" MODIFY ("ROLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VILLE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."VILLE" ADD CONSTRAINT "VILLE_PK" PRIMARY KEY ("VALEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PIPELINE"."VILLE" MODIFY ("VALEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POINT
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."POINT" MODIFY ("ID_POINT_ENUM" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."POINT" MODIFY ("VALEUR" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."POINT" ADD CONSTRAINT "POINT_PK" PRIMARY KEY ("ID_POINT_ENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DROIT
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."DROIT" ADD CONSTRAINT "DROIT_PK" PRIMARY KEY ("ID_DROIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIPELINE"  ENABLE;
  ALTER TABLE "PIPELINE"."DROIT" MODIFY ("PRIVILEGE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."DROIT" MODIFY ("TABLE_DROIT" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."DROIT" MODIFY ("ID_DROIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ABONNEMENT
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."ABONNEMENT" MODIFY ("ID_RENCONTRE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."ABONNEMENT" MODIFY ("ID_TOURNOI" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."ABONNEMENT" MODIFY ("ID_UTILISATEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NIVEAU
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."NIVEAU" MODIFY ("VALEUR" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."NIVEAU" ADD CONSTRAINT "NIVEAU_PK" PRIMARY KEY ("VALEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORGANISATION
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."ORGANISATION" MODIFY ("ID_TOURNOI" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."ORGANISATION" MODIFY ("ID_RENCONTRE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."ORGANISATION" MODIFY ("ID_USER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPLEXE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."COMPLEXE" MODIFY ("ID_COMPLEXE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."COMPLEXE" ADD CONSTRAINT "COMPLEXE_PK" PRIMARY KEY ("ID_COMPLEXE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."ROLE" MODIFY ("VALEUR" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."ROLE" ADD CONSTRAINT "ROLE_PK" PRIMARY KEY ("VALEUR")
  USING INDEX (CREATE UNIQUE INDEX "PIPELINE"."ROLE_PK1" ON "PIPELINE"."ROLE" ("VALEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENEMENT
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."EVENEMENT" MODIFY ("ID_JOUEUR" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."EVENEMENT" MODIFY ("ID_EVENEMENT" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."EVENEMENT" ADD CONSTRAINT "EVENEMENT_PK" PRIMARY KEY ("ID_EVENEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JEU_MATCH
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."JEU_MATCH" MODIFY ("ID_SET" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."JEU_MATCH" MODIFY ("ID_JEU" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."JEU_MATCH" ADD CONSTRAINT "JEU_MATCH_PK" PRIMARY KEY ("ID_JEU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RENCONTRE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."RENCONTRE" MODIFY ("ID_COURT" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."RENCONTRE" MODIFY ("ID_ARBITRE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."RENCONTRE" MODIFY ("ID_EQUIPE_DEUX" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."RENCONTRE" MODIFY ("ID_EQUIPE_UNE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."RENCONTRE" MODIFY ("ID_RENCONTRE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."RENCONTRE" ADD CONSTRAINT "RENCONTRE_PK" PRIMARY KEY ("ID_RENCONTRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRIVILEGE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."PRIVILEGE" ADD CONSTRAINT "PRIVILEGE_PK" PRIMARY KEY ("VALEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIPELINE"  ENABLE;
  ALTER TABLE "PIPELINE"."PRIVILEGE" MODIFY ("VALEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."UTILISATEUR" MODIFY ("ID_UTILISATEUR" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."UTILISATEUR" ADD CONSTRAINT "PK_ID_UTILISATEUR" PRIMARY KEY ("ID_UTILISATEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."EQUIPE" MODIFY ("ID_EQUIPE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."EQUIPE" ADD CONSTRAINT "EQUIPE_PK" PRIMARY KEY ("ID_EQUIPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TYPE_EVENEMENT
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."TYPE_EVENEMENT" ADD CONSTRAINT "TYPE_EVENEMENT_PK" PRIMARY KEY ("VALEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PIPELINE"."TYPE_EVENEMENT" MODIFY ("VALEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOUEUR
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."JOUEUR" MODIFY ("ID_JOUEUR" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."JOUEUR" ADD CONSTRAINT "JOUEUR_PK" PRIMARY KEY ("ID_JOUEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADRESSE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."ADRESSE" MODIFY ("ID_ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."ADRESSE" ADD CONSTRAINT "ADRESSE_PK" PRIMARY KEY ("ID_ADRESSE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RENCONTRE_EQUIPE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."RENCONTRE_EQUIPE" ADD CONSTRAINT "RENCONTRE_EQUIPE_PK" PRIMARY KEY ("ID_RENCONTRE_EQUIPE")
  USING INDEX (CREATE UNIQUE INDEX "PIPELINE"."RENCONTREEQUIPE_PK" ON "PIPELINE"."RENCONTRE_EQUIPE" ("ID_RENCONTRE_EQUIPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PIPELINE" )  ENABLE;
  ALTER TABLE "PIPELINE"."RENCONTRE_EQUIPE" MODIFY ("ID_RENCONTRE_EQUIPE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."RENCONTRE_EQUIPE" MODIFY ("ID_EQUIPE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."RENCONTRE_EQUIPE" MODIFY ("ID_RENCONTRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOURNOI
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."TOURNOI" ADD CONSTRAINT "TOURNOI_PK" PRIMARY KEY ("ID_TOURNOI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PIPELINE"."TOURNOI" MODIFY ("ID_TOURNOI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURT
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."COURT" MODIFY ("ID_COMPLEXE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."COURT" MODIFY ("ID_COURT" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."COURT" ADD CONSTRAINT "COURT_PK" PRIMARY KEY ("ID_COURT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TYPE_COURT
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."TYPE_COURT" ADD CONSTRAINT "TYPE_COURT_PK" PRIMARY KEY ("VALEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PIPELINE"."TYPE_COURT" MODIFY ("VALEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PHASE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."PHASE" MODIFY ("ID_RENCONTRE" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."PHASE" ADD CONSTRAINT "PHASE_PK" PRIMARY KEY ("ID_PHASE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SET_MATCH
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."SET_MATCH" MODIFY ("ID_SET" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."SET_MATCH" ADD CONSTRAINT "SET_MATCH_PK" PRIMARY KEY ("ID_SET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PIPELINE"."SET_MATCH" MODIFY ("ID_RENCONTRE_EQUIPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POINT_MATCH
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."POINT_MATCH" MODIFY ("ID_POINT_ENUMERATION" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."POINT_MATCH" MODIFY ("ID_JEU" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."POINT_MATCH" MODIFY ("ID_POINT" NOT NULL ENABLE);
  ALTER TABLE "PIPELINE"."POINT_MATCH" ADD CONSTRAINT "POINT_MATCH_PK" PRIMARY KEY ("ID_POINT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ABONNEMENT
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."ABONNEMENT" ADD CONSTRAINT "FK_ABONNEMENT_ID_RENCONTRE" FOREIGN KEY ("ID_RENCONTRE")
	  REFERENCES "PIPELINE"."RENCONTRE" ("ID_RENCONTRE") ENABLE;
  ALTER TABLE "PIPELINE"."ABONNEMENT" ADD CONSTRAINT "FK_ABONNEMENT_ID_TOURNOI" FOREIGN KEY ("ID_TOURNOI")
	  REFERENCES "PIPELINE"."TOURNOI" ("ID_TOURNOI") ENABLE;
  ALTER TABLE "PIPELINE"."ABONNEMENT" ADD CONSTRAINT "FK_ABONNEMENT_ID_UTILISATEUR" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES "PIPELINE"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COURT
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."COURT" ADD CONSTRAINT "FK_COURT_ID_COMPLEXE" FOREIGN KEY ("ID_COMPLEXE")
	  REFERENCES "PIPELINE"."COMPLEXE" ("ID_COMPLEXE") ENABLE;
  ALTER TABLE "PIPELINE"."COURT" ADD CONSTRAINT "FK_COURT_TYPE" FOREIGN KEY ("TYPE")
	  REFERENCES "PIPELINE"."TYPE_COURT" ("VALEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DROIT
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."DROIT" ADD CONSTRAINT "DROIT_FK1" FOREIGN KEY ("PRIVILEGE")
	  REFERENCES "PIPELINE"."PRIVILEGE" ("VALEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DROIT_ROLE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."DROIT_ROLE" ADD CONSTRAINT "DROIT_ROLE_FK1" FOREIGN KEY ("ID_DROIT")
	  REFERENCES "PIPELINE"."DROIT" ("ID_DROIT") ENABLE;
  ALTER TABLE "PIPELINE"."DROIT_ROLE" ADD CONSTRAINT "DROIT_ROLE_FK2" FOREIGN KEY ("ROLE")
	  REFERENCES "PIPELINE"."ROLE" ("VALEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIJOU
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."EQUIJOU" ADD CONSTRAINT "EQUIJOU_FK_ID_EQUIPE" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "PIPELINE"."EQUIPE" ("ID_EQUIPE") ENABLE;
  ALTER TABLE "PIPELINE"."EQUIJOU" ADD CONSTRAINT "EQUIJOU_FK_ID_JOUEUR" FOREIGN KEY ("ID_JOUEUR")
	  REFERENCES "PIPELINE"."JOUEUR" ("ID_JOUEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENEMENT
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."EVENEMENT" ADD CONSTRAINT "FK_EVENEMENT_TYPE" FOREIGN KEY ("TYPE")
	  REFERENCES "PIPELINE"."TYPE_EVENEMENT" ("VALEUR") ENABLE;
  ALTER TABLE "PIPELINE"."EVENEMENT" ADD CONSTRAINT "FK_ID_JOUEUR" FOREIGN KEY ("ID_JOUEUR")
	  REFERENCES "PIPELINE"."JOUEUR" ("ID_JOUEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JEU_MATCH
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."JEU_MATCH" ADD CONSTRAINT "FK_JEU_MATCH_ID_SET" FOREIGN KEY ("ID_SET")
	  REFERENCES "PIPELINE"."SET_MATCH" ("ID_SET") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORGANISATION
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_ID_RENCONTRE" FOREIGN KEY ("ID_RENCONTRE")
	  REFERENCES "PIPELINE"."RENCONTRE" ("ID_RENCONTRE") ENABLE;
  ALTER TABLE "PIPELINE"."ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_ID_TOURNOI" FOREIGN KEY ("ID_TOURNOI")
	  REFERENCES "PIPELINE"."TOURNOI" ("ID_TOURNOI") ENABLE;
  ALTER TABLE "PIPELINE"."ORGANISATION" ADD CONSTRAINT "FK_ORGANISATION_ID_USER" FOREIGN KEY ("ID_USER")
	  REFERENCES "PIPELINE"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHASE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."PHASE" ADD CONSTRAINT "FK_PHASE_ID_RENCONTRE" FOREIGN KEY ("ID_RENCONTRE")
	  REFERENCES "PIPELINE"."RENCONTRE" ("ID_RENCONTRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POINT_MATCH
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."POINT_MATCH" ADD CONSTRAINT "FK_POINT_ID_POINT_ENUM" FOREIGN KEY ("ID_POINT_ENUMERATION")
	  REFERENCES "PIPELINE"."POINT" ("ID_POINT_ENUM") ENABLE;
  ALTER TABLE "PIPELINE"."POINT_MATCH" ADD CONSTRAINT "FK_POINT_MATCH_ID_JEU" FOREIGN KEY ("ID_JEU")
	  REFERENCES "PIPELINE"."JEU_MATCH" ("ID_JEU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RENCONTRE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."RENCONTRE" ADD CONSTRAINT "FK_RENCONTRE_ID_ARBITRE" FOREIGN KEY ("ID_ARBITRE")
	  REFERENCES "PIPELINE"."UTILISATEUR" ("ID_UTILISATEUR") ENABLE;
  ALTER TABLE "PIPELINE"."RENCONTRE" ADD CONSTRAINT "FK_RENCONTRE_ID_COURT" FOREIGN KEY ("ID_COURT")
	  REFERENCES "PIPELINE"."COURT" ("ID_COURT") ENABLE;
  ALTER TABLE "PIPELINE"."RENCONTRE" ADD CONSTRAINT "FK_RENCONTRE_ID_EQUIPE_DEUX" FOREIGN KEY ("ID_EQUIPE_DEUX")
	  REFERENCES "PIPELINE"."JOUEUR" ("ID_JOUEUR") ENABLE;
  ALTER TABLE "PIPELINE"."RENCONTRE" ADD CONSTRAINT "FK_RENCONTRE_ID_EQUIPE_UNE" FOREIGN KEY ("ID_EQUIPE_UNE")
	  REFERENCES "PIPELINE"."EQUIPE" ("ID_EQUIPE") ENABLE;
  ALTER TABLE "PIPELINE"."RENCONTRE" ADD CONSTRAINT "PK_RENCONTRE_ID_PHASE" FOREIGN KEY ("ID_PHASE")
	  REFERENCES "PIPELINE"."PHASE" ("ID_PHASE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RENCONTRE_EQUIPE
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."RENCONTRE_EQUIPE" ADD CONSTRAINT "FK_RE_EQUIPE" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "PIPELINE"."EQUIPE" ("ID_EQUIPE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PIPELINE"."RENCONTRE_EQUIPE" ADD CONSTRAINT "FK_RE_RENCONTRE" FOREIGN KEY ("ID_RENCONTRE")
	  REFERENCES "PIPELINE"."RENCONTRE" ("ID_RENCONTRE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SET_MATCH
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."SET_MATCH" ADD CONSTRAINT "FK_SET_MATCH_RENCONTRE_EQUIPE" FOREIGN KEY ("ID_RENCONTRE_EQUIPE")
	  REFERENCES "PIPELINE"."RENCONTRE_EQUIPE" ("ID_RENCONTRE_EQUIPE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TOURNOI
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."TOURNOI" ADD CONSTRAINT "FK_TOURNOI_ID_COMPLEXE" FOREIGN KEY ("ID_COMPLEXE")
	  REFERENCES "PIPELINE"."COMPLEXE" ("ID_COMPLEXE") ENABLE;
  ALTER TABLE "PIPELINE"."TOURNOI" ADD CONSTRAINT "FK_TOURNOI_NIVEAU" FOREIGN KEY ("NIVEAU")
	  REFERENCES "PIPELINE"."NIVEAU" ("VALEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "PIPELINE"."UTILISATEUR" ADD CONSTRAINT "FK_ROLE" FOREIGN KEY ("ROLE")
	  REFERENCES "PIPELINE"."ROLE" ("VALEUR") ENABLE;
