export default {
  HOME: 'Home',
  ABOUT: 'About',
  MATCH: 'Match',
  MATCHS: 'Matchs',
  LADDER: 'Ladder',
  CALENDAR: 'Calendar',
  SETTINGS: 'Settings',
  PROFILE: 'Profile',
  TOURNAMENTS: 'Tournaments',
  TOURNAMENT: 'Tournament',
  ADDTOURNAMENT: 'Add Tournament',
  ERROR_404: '404',
  ORGANISER: 'Organiser',
  IMPORTER: 'Importer',
  RANKINGS: 'Rankings',
};
